Allow for undefined command param on ensure => absent
Before this change, declaring a sensu::check to be absent with no command would fail:

```
  sensu::check {
    'check_system_raid':
      ensure => 'absent';
  }
```
The above would cause:
```
Error: Could not retrieve catalog from remote server:
Error 400 on SERVER:
Evaluation Error:
Error while evaluating a Resource Statement, Sensu::Check[check_system_raid]:
expects a value for parameter 'command' at [..] on node [...]
```

This commit allows for undefined `command` parameter which would be validated only if ensure is present (default), raising a specific error if command is missing.